service: curso-sls-hola-mundo

app: curso-sls-hola-mundo
org: angelgbcore

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
  helloUser:
    handler: handler.helloUser
    events:
      - http:
          method: GET
          path: /user/{name}
  createUser:
    handler: handler.createUser
    events:
      - http:
          method: POST
          path: /user